admin.login:
    pattern: /admin/login
    defaults: { _controller: CmsBundle:AdminSecurity:login }

admin.login_check:
    pattern: /admin/login_check

admin.logout:
    pattern: /admin/logout

admin.dashboard:
    pattern: /admin/
    defaults: { _controller: CmsBundle:AdminDashboard:index }

admin.files:
    pattern: /admin/files/
    defaults: { _controller: CmsBundle:AdminFiles:index }

admin.accounts:
    pattern: /admin/accounts/
    defaults: { _controller: CmsBundle:AdminAccounts:index }

admin.style:
    pattern: /admin/style/
    defaults: { _controller: CmsBundle:AdminStyle:index }

admin.settings:
    pattern: /admin/settings/
    defaults: { _controller: CmsBundle:AdminSettings:index }


main:
    pattern:  /
    defaults: { _controller: CmsBundle:Legacy:index }

_legacy:
    pattern:  /{path}
    defaults: { _controller: CmsBundle:Legacy:index }
    requirements:
        path: ".+"
