admin.login:
    pattern: /admin/login
    defaults: { _controller: CmsBundle:AdminSecurity:login }

admin.login_check:
    pattern: /admin/login_check

admin.logout:
    pattern: /admin/logout

admin.dashboard:
    pattern: /admin/
    defaults: { _controller: CmsBundle:AdminDashboard:index }

admin.settings:
    pattern: /admin/settings
    defaults: { _controller: CmsBundle:AdminSettings:index }

admin.accounts:
    pattern: /admin/accounts
    defaults: { _controller: CmsBundle:AdminAccounts:index }


main:
    pattern:  /
    defaults: { _controller: CmsBundle:Legacy:index }

_legacy:
    pattern:  /{path}
    defaults: { _controller: CmsBundle:Legacy:index }
    requirements:
        path: ".+"
