jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        admin:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: admin.login
                check_path: admin.login_check
                username_parameter: username
                password_parameter: password
            logout:
                path: /admin/logout
                target: /
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 дней
                path: /
                domain: ~
                remember_me_parameter: autologin

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
-