admin.login:
    pattern: /admin/login
    defaults: { _controller: CmsBundle:AdminSecurity:login }

admin.login_check:
    pattern: /admin/login_check

admin.logout:
    pattern: /admin/logout

admin.dashboard:
    pattern: /admin/
    defaults: { _controller: CmsBundle:AdminDashboard:index }

admin.content:
    pattern: /admin/content/
    defaults: { _controller: CmsBundle:AdminContent:index }

admin.content.add:
    pattern: /admin/content/{parent}/add
    defaults: { _controller: CmsBundle:AdminContent:add }

admin.content.edit:
    pattern: /admin/content/{id}/
    defaults: { _controller: CmsBundle:AdminContent:edit }

admin.content.properties:
    pattern: /admin/content/{id}/properties
    defaults: { _controller: CmsBundle:AdminContent:properties }

admin.content.up:
    pattern: /admin/content/{id}/up
    defaults: { _controller: CmsBundle:AdminContent:up }

admin.content.down:
    pattern: /admin/content/{id}/down
    defaults: { _controller: CmsBundle:AdminContent:down }

admin.content.move:
    pattern: /admin/content/{id}/move
    defaults: { _controller: CmsBundle:AdminContent:move }

admin.content.delete:
    pattern: /admin/content/{id}/
    defaults: { _controller: CmsBundle:AdminContent:edit }

admin.files:
    pattern: /admin/files/
    defaults: { _controller: CmsBundle:AdminFiles:index }

admin.settings:
    pattern: /admin/settings/
    defaults: { _controller: CmsBundle:AdminSettings:index }

admin.accounts:
    pattern: /admin/settings/accounts/
    defaults: { _controller: CmsBundle:AdminSettings:accounts }

admin.style:
    pattern: /admin/settings/style/
    defaults: { _controller: CmsBundle:AdminSettings:style }

admin.plugins:
    pattern: /admin/settings/plugins/
    defaults: { _controller: CmsBundle:AdminPlugins:index }

admin.plugins.install:
    pattern: /admin/settings/plugins/install
    defaults: { _controller: CmsBundle:AdminPlugins:install }

admin.plugins.config:
    pattern: /admin/settings/plugins/{id}/config
    defaults: { _controller: CmsBundle:AdminPlugins:config }

admin.plugins.toggle:
    pattern: /admin/settings/plugins/{id}/toggle
    defaults: { _controller: CmsBundle:AdminPlugins:toggle }

admin.plugins.uninstall:
    pattern: /admin/settings/plugins/{id}/uninstall
    defaults: { _controller: CmsBundle:AdminPlugins:uninstall }

main:
    pattern:  /
    defaults: { _controller: CmsBundle:Legacy:index }

_legacy:
    pattern:  /{path}
    defaults: { _controller: CmsBundle:Legacy:index }
    requirements:
        path: ".+"
